name: 晓月刀的博客
description: 多动手、勤思考
meta_description: "晓月刀的博客"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'http://blog.justtodo.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog.justtodo.com'
author:         'xiao_dli'
