name: 晓月刀的博客
description: 多动手、勤思考
meta_description: "晓月刀的博客"

gems:
  - jekyll-paginate
  - jekyll-feed
markdown: redcarpet
highlighter: pygments
logo: false
paginate: 2
baseurl: /
domain_name: 'http://blog.justtodo.com'
google_analytics: 'UA-XXXXXXXX-X'
favicon: '/assets/images/favicon.ico'

# Details for the RSS feed generator
url:            'blog.justtodo.com'
author:         'xiao_dli'
